server {
    listen 80;
    listen [::]:80;
    server_name qr.akadmvd.uz;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name qr.akadmvd.uz;

    ssl_certificate /etc/letsencrypt/live/qr.akadmvd.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qr.akadmvd.uz/privkey.pem;

    client_max_body_size 100M;

    location /static/ {
        alias /var/www/qrcode/staticfiles/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /var/www/qrcode/media/;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
