# Generated by Django 6.0.3 on 2026-04-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='qrcode')),
                ('qrimg', models.ImageField(upload_to='qrcode')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcode.faculty')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcode.teacher')),
            ],
        ),
    ]
