# Generated by Codex on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("about", models.TextField()),
                ("audio", models.FileField(upload_to="qrcode")),
                ("video", models.FileField(upload_to="qrcode")),
                ("qrcode", models.ImageField(upload_to="qrcode")),
                ("item", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="about_entry", to="qrcode.qrcode")),
            ],
        ),
    ]
