# Generated by Codex on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0002_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="qr_codes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunSQL(
            sql="UPDATE qrcode_about SET item_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="about",
            name="item",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="about_entry", to="qrcode.product"),
        ),
    ]
