# Generated by Codex on 2026-04-04

from django.db import migrations
from django.utils.text import slugify


def copy_legacy_qrcodes(apps, schema_editor):
    Product = apps.get_model("qrcode", "Product")
    LegacyQRCode = apps.get_model("qrcode", "QRCode")

    if Product.objects.exists():
        return

    used_slugs = set()
    for legacy in LegacyQRCode.objects.all().order_by("id"):
        base_slug = slugify(legacy.name) or f"item-{legacy.id}"
        slug = base_slug
        counter = 2
        while slug in used_slugs or Product.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        product = Product(name=legacy.name, slug=slug)
        if hasattr(legacy, "qrimg") and legacy.qrimg:
            product.qr_code = legacy.qrimg
        product.save()
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0003_product_and_about_update"),
    ]

    operations = [
        migrations.RunPython(copy_legacy_qrcodes, migrations.RunPython.noop),
    ]
