# Generated by Codex on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0004_copy_legacy_qrcodes_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="faculty",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="qrcode.faculty"),
        ),
        migrations.AddField(
            model_name="product",
            name="teacher",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="qrcode.teacher"),
        ),
    ]
