# Generated by Django 6.0.2 on 2026-04-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0005_product_faculty_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
