# Generated by Codex on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0006_remove_product_slug_delete_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="qrcode"),
        ),
    ]
