# Generated by Codex on 2026-04-04

from django.db import migrations, models


def copy_existing_content_to_uzbek(apps, schema_editor):
    Product = apps.get_model("qrcode", "Product")
    About = apps.get_model("qrcode", "About")

    for product in Product.objects.all():
        product.name_uz = product.name_uz or ""
        product.description_uz = product.description_uz or product.description_ru or product.description_en or ""
        product.save(
            update_fields=[
                "name_uz",
                "description_uz",
            ]
        )

    for about in About.objects.all():
        about.about_uz = about.about_uz or ""
        about.save(update_fields=["about_uz"])


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0008_category_and_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="name_uz",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="description_uz",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="about",
            new_name="about_uz",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="audio",
            new_name="audio_uz",
        ),
        migrations.RenameField(
            model_name="about",
            old_name="video",
            new_name="video_uz",
        ),
        migrations.AlterField(
            model_name="about",
            name="audio_uz",
            field=models.FileField(blank=True, null=True, upload_to="qrcode"),
        ),
        migrations.AlterField(
            model_name="about",
            name="video_uz",
            field=models.FileField(blank=True, null=True, upload_to="qrcode"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="about",
            name="about_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="about",
            name="about_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="about",
            name="audio_en",
            field=models.FileField(blank=True, null=True, upload_to="qrcode"),
        ),
        migrations.AddField(
            model_name="about",
            name="audio_ru",
            field=models.FileField(blank=True, null=True, upload_to="qrcode"),
        ),
        migrations.AddField(
            model_name="about",
            name="video_en",
            field=models.FileField(blank=True, null=True, upload_to="qrcode"),
        ),
        migrations.AddField(
            model_name="about",
            name="video_ru",
            field=models.FileField(blank=True, null=True, upload_to="qrcode"),
        ),
        migrations.RunPython(copy_existing_content_to_uzbek, migrations.RunPython.noop),
    ]
