# Generated by Codex on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0009_multilingual_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="audio_en",
            field=models.FileField(blank=True, null=True, upload_to="qrcodes/"),
        ),
        migrations.AddField(
            model_name="product",
            name="audio_ru",
            field=models.FileField(blank=True, null=True, upload_to="qrcodes/"),
        ),
        migrations.AddField(
            model_name="product",
            name="audio_uz",
            field=models.FileField(blank=True, null=True, upload_to="qrcodes/"),
        ),
        migrations.AddField(
            model_name="product",
            name="video_en",
            field=models.FileField(blank=True, null=True, upload_to="qrcodes/"),
        ),
        migrations.AddField(
            model_name="product",
            name="video_ru",
            field=models.FileField(blank=True, null=True, upload_to="qrcodes/"),
        ),
        migrations.AddField(
            model_name="product",
            name="video_uz",
            field=models.FileField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
