# Generated by Codex on 2026-04-06

from django.db import migrations


def seed_translations(apps, schema_editor):
    Category = apps.get_model("qrcode", "Category")
    Faculty = apps.get_model("qrcode", "Faculty")

    category_translations = {
        "Texnologiyalar": ("Технологии", "Technologies"),
        "Mebellar": ("Мебель", "Furniture"),
        "moddiy boyliklar": ("Материальные ценности", "Material assets"),
    }
    faculty_translations = {
        "Ekspert_Kriminalistika": ("Экспертная криминалистика", "Forensic science"),
        "Tergov Faoliyati": ("Следственная деятельность", "Investigative activity"),
    }

    for source_name, (name_ru, name_en) in category_translations.items():
        Category.objects.filter(name=source_name, name_ru="", name_en="").update(
            name_ru=name_ru,
            name_en=name_en,
        )

    for source_name, (name_ru, name_en) in faculty_translations.items():
        Faculty.objects.filter(name=source_name, name_ru="", name_en="").update(
            name_ru=name_ru,
            name_en=name_en,
        )


def clear_seeded_translations(apps, schema_editor):
    Category = apps.get_model("qrcode", "Category")
    Faculty = apps.get_model("qrcode", "Faculty")

    Category.objects.filter(name="Texnologiyalar").update(name_ru="", name_en="")
    Category.objects.filter(name="Mebellar").update(name_ru="", name_en="")
    Category.objects.filter(name="moddiy boyliklar").update(name_ru="", name_en="")

    Faculty.objects.filter(name="Ekspert_Kriminalistika").update(name_ru="", name_en="")
    Faculty.objects.filter(name="Tergov Faoliyati").update(name_ru="", name_en="")


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode", "0011_category_name_en_category_name_ru_faculty_name_en_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_translations, clear_seeded_translations),
    ]
