# Generated by Django 6.0.3 on 2026-04-07 12:31

import qrcode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0012_seed_translations_for_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentTtsAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=8)),
                ('provider', models.CharField(db_index=True, max_length=120)),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('source_text', models.TextField()),
                ('content_type', models.CharField(default='audio/mpeg', max_length=64)),
                ('extension', models.CharField(default='mp3', max_length=16)),
                ('audio_file', models.FileField(upload_to=qrcode.models.tts_cache_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'provider', 'text_hash'), name='unique_persistent_tts_audio_entry')],
            },
        ),
    ]
