# Generated by Django 6.0.3 on 2026-04-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0014_persistentttsaudio_audio_blob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='persistentttsaudio',
            name='unique_persistent_tts_audio_entry',
        ),
        migrations.DeleteModel(
            name='PersistentTtsAudio',
        ),
    ]
