"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s=zt&4n=(1i$l44hnh6(xtruo3!)@5$tc5u29st3$#8lfkyg0p'

# SECURITY WARNING: don't run with debug turned on in production!


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


DEBUG = env_bool("DEBUG", True)
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", True)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


def env_list(name, default):
    value = os.getenv(name)
    if not value:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


def normalize_origin(url):
    parts = urlsplit(url)
    if parts.scheme and parts.netloc:
        return f"{parts.scheme}://{parts.netloc}"
    return str(url).rstrip("/")


ALLOWED_HOSTS = ['*']
DEFAULT_PUBLIC_URL = "https://qr.akadmvd.uz"
BACKEND_URL = os.getenv("BACKEND_URL", DEFAULT_PUBLIC_URL).rstrip("/")
FRONTEND_URL = os.getenv("FRONTEND_URL", DEFAULT_PUBLIC_URL).rstrip("/")
FRONTEND_ALLOWED_ORIGINS = [
    normalize_origin(origin)
    for origin in env_list(
        "FRONTEND_ALLOWED_ORIGINS",
        [
            FRONTEND_URL,
            "http://localhost:4173",
            "http://localhost:5173",
        ],
    )
]
CSRF_TRUSTED_ORIGINS = FRONTEND_ALLOWED_ORIGINS
SITE_URL = BACKEND_URL
YANDEX_TTS_API_KEY = os.getenv("YANDEX_TTS_API_KEY", "").strip()
YANDEX_TTS_API_URL = os.getenv("YANDEX_TTS_API_URL", "https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize").strip()
YANDEX_TTS_UZ_VOICE = os.getenv("YANDEX_TTS_UZ_VOICE", "yulduz").strip() or "yulduz"
YANDEX_TTS_TIMEOUT = float(os.getenv("YANDEX_TTS_TIMEOUT", "20"))
EDGE_TTS_UZ_VOICE = os.getenv("EDGE_TTS_UZ_VOICE", "uz-UZ-MadinaNeural").strip() or "uz-UZ-MadinaNeural"
EDGE_TTS_RU_VOICE = os.getenv("EDGE_TTS_RU_VOICE", "ru-RU-SvetlanaNeural").strip() or "ru-RU-SvetlanaNeural"
EDGE_TTS_EN_VOICE = os.getenv("EDGE_TTS_EN_VOICE", "en-US-JennyNeural").strip() or "en-US-JennyNeural"
TTS_CACHE_TIMEOUT = int(os.getenv("TTS_CACHE_TIMEOUT", "86400"))
API_RESPONSE_CACHE_TIMEOUT = int(os.getenv("API_RESPONSE_CACHE_TIMEOUT", "120"))
LOOKUP_RESPONSE_CACHE_TIMEOUT = int(os.getenv("LOOKUP_RESPONSE_CACHE_TIMEOUT", "900"))


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'qrcode',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'core.cors.SimpleCORSMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

LANGUAGES = [
    ('uz', "O'zbek"),
    ('ru', 'Russian'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
STATICFILES_DIRS = []
STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "qr-catalog-default-cache",
    }
}

